[pytest]
addopts = -v -s
testpaths = tests
python_files = test_*.py

markers =
    login: Tests related to login
    inbox: Tests related to inbox page
    compose: Tests related to composing and sending emails
