[pytest]
addopts = -v -s -ra -q
testpaths = tests
python_files = test_*.py
pythonpath = .

markers =
    login: Tests related to login
    inbox: Tests related to inbox page
    compose: Tests related to composing and sending emails
